# SASS Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  formatter: stylish

# File Options
files:
  include: 'sass/**/*.s+(a|c)ss'
  ignore:
    - 'sass/vendor/**/*.*'

# Rule Configuration
rules:
  brace-style:
    - 2
    -
      style:
        - 'stroustrup'
      allow-single-line:
        - true

  clean-import-paths: 0
  declarations-before-nesting: 2
  empty-args: 0
  empty-line-between-blocks:
    - 2
    -
      include:
        - true
      allow-single-line-rulesets:
        - true

  extends-before-declarations: 2
  extends-before-mixins: 2
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format: 0
  hex-length: 0
  hex-notation:
    - 0
    -
      style: lowercase

  id-name-format: 0
  indentation:
    - 0
    -
      size: 2

  leading-zero: 0
  max-file-line-count: 0
  max-line-length: 0
  mixins-before-declarations:
    - 2
    -
      exclude:
        - media

  mixin-name-format: 0
  nesting-depth:
    - 2
    -
      max-depth:
        - 2

  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 2
  no-color-literals:
    - 2
    -
      allow-rgba:
        - true

  no-combinators: 0
  no-css-comments: 2
  no-disallowed-properties: 0
  no-duplicate-properties:
  - 2
  -
    exclude:
      - margin
      - padding

  no-empty-rulesets: 2
  no-extends: 0
  no-warn: 2
  no-debug: 2
  no-ids: 1
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 1
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 1
    -
      allow-element-with-attribute:
        - true
  no-trailing-whitespace: 2
  no-trailing-zero: 0
  no-transition-all: 2
  no-universal-selectors: 0
  no-url-domains: 2
  no-url-protocols: 2
  no-vendor-prefixes: 2
  one-declaration-per-line: 2
  placeholder-in-extend: 0
  placeholder-name-format: 0
  property-sort-order:
    - 2
    -
      order:
        - content
        - display
        - position
        - float
      ignore-custom-properties: true

  property-units: 0
  pseudo-element: 0
  quotes: 0
  shorthand-values:
    - 2
    -
      allowed-shorthands:
        - 1
        - 2

  single-line-per-selector: 2
  space-after-bang: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 0
  trailing-semicolon: 2
  url-quotes: 2
  variable-for-property: 0
  variable-name-format: 0
  zero-unit: 2
